Add shoulder-tap functionality
aeristhings/aeris-modsdk-py pull request #6
Opened 2020-08-10 17:44 UTC by ethaeris

2020-09-14 18:14 UTC, ethaeris commented
@drewjohnsonataeris and @sundararunachal : I'll be merging this PR tomorrow. 
There was a merge conflict in aerismodsdk/utils/rmutils.py's wait_urc function.

2020-09-15 14:47 UTC, sundararunachal requested changes

2020-09-15 14:47 UTC, sundararunachal commented on aerismodsdk/shoulder_tap.py
> +def get_shoulder_taps(module, port=23747, verbose=False):
I prefer to move this get_shoulder_taps functionality to base module instead of having a separate python script as it is a generic method for all modules.    
  
parse_shoulder_tap method is a utility function, so move it to utils. 

I see udp_urcs_to_payloads is implemented only in Quectel.   So I suggest to override it in other modules and give a warning that this function is not supported in that module.

2020-09-15 14:48 UTC, sundararunachal commented
> @drewjohnsonataeris and @sundararunachal : I'll be merging this PR tomorrow.
> There was a merge conflict in aerismodsdk/utils/rmutils.py's wait_urc function.

My bad,   I added the review comments but seems like i need to submit as well.    Can you please address the review comments before merging it.

2020-10-02 23:24 UTC, ethaeris commented on aerismodsdk/shoulder_tap.py
> +def get_shoulder_taps(module, port=23747, verbose=False):
OK, I believe I've resolved your comments. 
Let me try this "Resolve conversation" button...

2020-10-21 18:59 UTC, merged